# Generated by Django 2.1.2 on 2018-11-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realter',
            new_name='Realtor',
        ),
    ]
