# Generated by Django 2.1.2 on 2018-11-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181120_1407'),
        ('realtors', '0002_auto_20181120_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtor',
            new_name='Realter',
        ),
    ]
